---
version: '3.4'
services:
  casecrafter:
    image: chatgpt_retrieval_plugin:latest
    ports:
    - 8000:8000
    restart: on-failure:0
    environment:
      DATASTORE: 'weaviate'
      BEARER_TOKEN: ${BEARER_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEAVIATE_HOST: 'http://127.0.0.1'
      WEAVIATE_PORT: '8080'
      WEAVIATE_INDEX: 'OpenAIDocument'
      WEAVIATE_BATCH_SIZE: '20'
      WEAVIATE_BATCH_DYNAMIC: 'False'
      WEAVIATE_BATCH_TIMEOUT_RETRIES: '3'
      WEAVIATE_BATCH_NUM_WORKERS: '1'
...